apiVersion: v1
kind: Service
metadata:
  name: notejam
  labels:
    app: notejam
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8080
      targetPort: 8080
  selector:
    app: notejam
    tier: app

